{
 "title": "WireGuard Dashboard",
 "description": "Dashboard for monitoring WireGuard with enhanced visualizations.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Active WireGuard Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(wireguard_peer_latest_handshake > time() - 300)",
     "legendFormat": "Active Peers"
    }
   ]
  },
  {
   "title": "Interface Load WG (Input/Output)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(interfaces_received_bytes_total[$__rate_interval])",
     "legendFormat": "Received: {{name}}"
    },
    {
     "expr": "rate(interfaces_transmitted_bytes_total[$__rate_interval])",
     "legendFormat": "Transmitted: {{name}}"
    }
   ]
  },
  {
   "title": "WireGuard Peer Received Bytes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, wireguard_peer_transfer_rx_bytes)\n",
     "legendFormat": "{{peer_name}}"
    }
   ]
  },
  {
   "title": "WireGuard Peer Transmitted Bytes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, wireguard_peer_transfer_tx_bytes)\n",
     "legendFormat": "{{peer_name}}"
    }
   ]
  },
  {
   "title": "Last Handshake Time",
   "type": "heatmap",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(wireguard_peer_latest_handshake[15m]) > 0",
     "legendFormat": "{{peer_name}}"
    }
   ]
  },
  {
   "title": "Inactive Peers (Last Month)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(peer_name) (rate(wireguard_peer_latest_handshake[720h])) == 0",
     "legendFormat": "{{peer_name}}"
    }
   ]
  },
  {
   "title": "WireGuard Peer Country Distribution",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(wireguard_peer_country_code) by (country_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Peers with Real IPs",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 56 },
   "targets": [
    {
     "expr": "sum by (peer_name, country_code) (wireguard_peer_country_code{country_code!=\"unknown\"})",
     "legendFormat": "{{peer_name}}: {{country_code}}"
    }
   ]
  }
 ]
}